version: '3'
services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 16379:6379
  mysql:
    image: mariadb
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_pass
      MYSQL_DATABASE: db_name
      MYSQL_USER: user_name
      MYSQL_PASSWORD: user_pass
    restart: always
  unit:
    build: ./unit
    volumes:
      - ./wordpress:/var/www/
      - ./unit/state":/var/lib/unit
    depends_on:
      - mysql
      - redis
    environment:
      WORDPRESS_DB_HOST: mysql
      MYSQL_ROOT_PASSWORD: mysql_root_pass
      WORDPRESS_DB_NAME: db_name
      WORDPRESS_DB_USER: user_name
      WORDPRESS_DB_PASSWORD: user_pass
      WORDPRESS_TABLE_PREFIX: wp_
    links:
      - mysql
      - redis
    restart: always
    ports:
      - 8080:8080
  nginx:
    build: ./nginx
    volumes:
      - ./nginx/config:/etc/nginx
      - ./wordpress:/var/www
    ports:
      - 80:80
    depends_on:
      - unit
    links:
      - unit
      - redis
